CREATE TABLE study_year (
                            id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name                  VARCHAR(50) NOT NULL UNIQUE,
                            position              INT         NOT NULL UNIQUE,
                            minimum_credit_points INT         NOT NULL
);